Adding sound
alexchung1233/SpookyStoreys pull request #61
Opened 2021-04-24 20:27 UTC by JackAkers

Added sound system and background music.  Also has monster AI and lose condition.

2021-04-26 00:41 UTC, alexchung1233 requested changes

2021-04-26 00:41 UTC, alexchung1233 commented on include/GameView.h
> +//=======
remove these merge conflict indicators

2021-04-26 00:41 UTC, alexchung1233 commented on include/GameView.h
> +//>>>>>>> main
remove this

2021-04-26 00:41 UTC, alexchung1233 commented on include/Menu.h
> +    Menu(sf::RenderWindow& app, Sound *sound);
we shouldn't need to pass a sound into the constructor

2021-04-26 00:41 UTC, alexchung1233 commented on src/GameView.cpp
> +//=======
remove this

2021-04-26 00:41 UTC, alexchung1233 commented on src/GameView.cpp
> +//<<<<<<< HEAD
remove this

2021-04-26 00:41 UTC, alexchung1233 commented on src/Menu.cpp
> +Menu::Menu(sf::RenderWindow& app, Sound* newSound){
shouldn't pass a sound the constructor

2021-04-26 00:41 UTC, alexchung1233 commented on src/Menu.cpp
> +        this->childState = new GameView(*App, sound);
shouldn't pass through GameView

2021-04-26 00:41 UTC, alexchung1233 commented on include/Menu.h
> +    Menu(sf::RenderWindow& app, Sound *sound);
I recommend making a setSound method inside State.h and having GameView, Menu, all the other states inherit from it.

2021-04-26 00:41 UTC, alexchung1233 commented on src/GameManager.cpp
> +  sound.init();
this should be in one of the other functions

2021-04-26 00:45 UTC, alexchung1233 requested changes

2021-04-26 00:45 UTC, alexchung1233 commented on src/Sound.cpp
> +
you should make a generic Sound constructor that takes in a file and lets you play it. Right now if you want to add a lightning sound, for instance, you have to make another function

2021-04-28 20:08 UTC, ktkel approved these changes

2021-04-29 01:18 UTC, alexchung1233 approved these changes

2021-04-29 01:42 UTC, merged